platform :ios, '9.0'

target 'TodoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoApp
pod 'RealmSwift', '5.5.0'
pod 'SwipeCellKit'
pod 'ChameleonFramework'

end
