platform :ios, '10.0'

target 'Bitcoin Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bitcoin Tracker
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'

end
